import { userSchema } from './user.zod';

// Generated by ts-to-zod
import { z } from "zod";
// @ts-ignore
export const postSchema = z.object({
    id: z.number(),
    title: z.string(),
    content: z.string().optional().nullable(),
    published: z.boolean(),
    authorId: z.number(),
    author: userSchema
});
